# Generated by Django 3.0 on 2024-11-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='bill_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='bill_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pracel',
            name='bill_time',
            field=models.TimeField(null=True),
        ),
    ]
